export const GET_ALL_DONATIONS = "GET_ALL_DONATIONS"
export const CREATE_DONATION = "CREATE_DONATION"
export const MODIFY_DONATION = "MODIFY_DONATION"
export const DELETE_DONATION = "DELETE_DONATION"
export const SET_CURRENT_USER = "SET_CURRENT_USER"



